#!/bin/sh -e

NAME="ASUS"
PASS="04071979"

log(){
	printf " :: $1"
}

die(){
	log "ERROR: $1"
	exit 1
}

main(){

log "Prepare"

if [ ! -d "/etc/iwd" ]; then
	install -dm755 /etc/iwd
fi

log "Create /etc/iwd/main.conf"

cat > /etc/iwd/main.conf << "EOF"
[General]
EnableNetworkConfiguration true
EOF

log "Generate psk from - $NAME"

printf $PASS | iwd_passphrase $NAME > /var/lib/iwd/${NAME}.psk

if [ -d "/etc/sv/eiwd" ]; then
	log "Add eiwd runit"
	ln -svf /etc/sv/eiwd /var/service/
fi

log "Restart eiwd"
sv restart eiwd

log "Done"
}

main "$@"
