#!/bin/sh -e

NAME=$1
PASS=$2

log(){
	printf " :: $1\n"
}

die(){
	log "ERROR: $1"
	exit 1
}

usage(){
	log "`basename $0` <name> <password>"
}

main(){

if [ "$1" = "" ]; then
	usage
	exit 1
elif [ "$2" = "" ]; then
	usage
	exit 1	
fi

log "Prepare"

if [ ! -d "/etc/iwd" ]; then
	install -dm755 /etc/iwd
fi

log "Create /etc/iwd/main.conf"

cat > /etc/iwd/main.conf << "EOF"
[General]
EnableNetworkConfiguration true
EOF

log "Generate psk from - $NAME"
install -dm755 /var/lib/iwd
printf $PASS | iwd_passphrase $NAME > /var/lib/iwd/${NAME}.psk

if [ -d "/etc/sv/eiwd" ]; then
	log "Add eiwd runit"
	ln -svf /etc/sv/eiwd /var/service/
fi

log "Restart eiwd"
sv restart eiwd

log "Done"
}

main "$@"
